/**
 * Payload CMS Generated Types
 * 
 * This file contains TypeScript types for Payload CMS collections.
 * In production, this file is auto-generated by running `payload generate:types`.
 * 
 * For now, we define the types manually based on our collection definitions.
 */

export interface Media {
  id: string
  alt?: string | null
  url?: string | null
  filename?: string | null
  mimeType?: string | null
  filesize?: number | null
  width?: number | null
  height?: number | null
  createdAt: string
  updatedAt: string
}

export interface Category {
  id: string
  name: string
  slug?: string | null
  description?: string | null
  image?: Media | string | null
  spec_fields?: Array<{
    name: string
    key: string
    type: 'text' | 'number' | 'select'
    unit?: string | null
    required?: boolean | null
    options?: Array<{ value: string }> | null
  }> | null
  createdAt: string
  updatedAt: string
}

export interface Product {
  id: string
  name: string
  slug?: string | null
  price: number
  short_description?: string | null
  is_active?: boolean | null
  stripe_product_id?: string | null
  stripe_price_id?: string | null
  category: Category | string
  description?: unknown // Rich text
  specs?: Array<{
    label: string
    value: string
    unit?: string | null
  }> | null
  features?: Array<{
    icon?: string | null
    title: string
    description?: string | null
  }> | null
  faq?: Array<{
    question: string
    answer?: unknown // Rich text
  }> | null
  main_image?: Media | string | null
  gallery?: Array<{
    image: Media | string
  }> | null
  blocks?: Array<Block> | null
  createdAt: string
  updatedAt: string
}

export interface Customer {
  id: string
  email: string
  name?: string | null
  phone?: string | null
  createdAt: string
  updatedAt: string
}

export interface Order {
  id: string
  order_number: string
  stripe_session_id?: string | null
  customer: Customer | string
  status: 'pending' | 'paid' | 'shipped' | 'delivered' | 'cancelled'
  amount: number
  shipping_address?: {
    line1?: string | null
    line2?: string | null
    city?: string | null
    postal_code?: string | null
    state?: string | null
    country?: string | null
  } | null
  billing_address?: {
    line1?: string | null
    line2?: string | null
    city?: string | null
    postal_code?: string | null
    state?: string | null
    country?: string | null
  } | null
  items?: Array<{
    product_name: string
    quantity: number
    unit_price: number
    product?: Product | string | null
  }> | null
  status_history?: Array<{
    status: string
    changed_at: string
    changed_by?: string | null
  }> | null
  createdAt: string
  updatedAt: string
}

export interface MaintenanceService {
  id: string
  name: string
  slug?: string | null
  description?: string | null
  price_monthly: number
  icon?: string | null
  includes?: Array<{ item: string }> | null
  is_active?: boolean | null
  sort_order?: number | null
  createdAt: string
  updatedAt: string
}

export interface MaintenanceOption {
  id: string
  name: string
  slug?: string | null
  description?: string | null
  price_monthly: number
  icon?: string | null
  is_active?: boolean | null
  is_flat_fee?: boolean | null
  exempt_from_discount?: boolean | null
  sort_order?: number | null
  createdAt: string
  updatedAt: string
}

export interface MaintenanceSubscription {
  id: string
  stripe_subscription_id: string
  customer: Customer | string
  billing_period: 'monthly' | 'annual'
  status: 'active' | 'cancelled' | 'past_due' | 'paused'
  totals?: {
    subtotal?: number | null
    discount_amount?: number | null
    total?: number | null
  } | null
  discounts?: {
    multi_service_discount?: number | null
    annual_discount?: number | null
  } | null
  items?: Array<{
    item_type: 'service' | 'option'
    name: string
    quantity: number
    unit_price: number
    service?: MaintenanceService | string | null
    option?: MaintenanceOption | string | null
  }> | null
  cancelled_at?: string | null
  createdAt: string
  updatedAt: string
}

export interface BlogPost {
  id: string
  title: string
  slug?: string | null
  excerpt?: string | null
  author?: string | null
  published_date?: string | null
  status: 'draft' | 'published'
  featured_image?: Media | string | null
  content?: unknown // Rich text
  seo?: {
    meta_title?: string | null
    meta_description?: string | null
    og_image?: Media | string | null
  } | null
  tags?: Array<{ tag: string }> | null
  createdAt: string
  updatedAt: string
}

export interface Page {
  id: string
  title: string
  slug?: string | null
  status: 'draft' | 'published'
  seo?: {
    meta_title?: string | null
    meta_description?: string | null
    og_image?: Media | string | null
  } | null
  blocks?: Array<Block> | null
  createdAt: string
  updatedAt: string
}

export interface User {
  id: string
  email: string
  role: 'admin' | 'editor'
  createdAt: string
  updatedAt: string
}

// Block types
export type Block =
  | HeroBlock
  | SpecsTableBlock
  | FAQBlock
  | GalleryBlock
  | ComparisonChartBlock
  | CTABlock
  | RichTextBlock

export interface HeroBlock {
  blockType: 'hero'
  heading: string
  subheading?: string | null
  background_image?: Media | string | null
  cta?: {
    text?: string | null
    url?: string | null
    style?: 'primary' | 'secondary' | null
  } | null
  alignment?: 'left' | 'center' | 'right' | null
  overlay?: boolean | null
}

export interface SpecsTableBlock {
  blockType: 'specs-table'
  title?: string | null
  auto_populate?: boolean | null
  specs?: Array<{ label: string; value: string }> | null
  columns?: number | null
}

export interface FAQBlock {
  blockType: 'faq'
  title?: string | null
  auto_populate?: boolean | null
  items?: Array<{ question: string; answer?: unknown }> | null
}

export interface GalleryBlock {
  blockType: 'gallery'
  title?: string | null
  columns?: '2' | '3' | '4' | null
  lightbox?: boolean | null
  auto_populate?: boolean | null
  images?: Array<{ image: Media | string; caption?: string | null }> | null
}

export interface ComparisonChartBlock {
  blockType: 'comparison-chart'
  title?: string | null
  columns: Array<{ header: string }>
  rows: Array<{
    feature: string
    cells: Array<{ value?: string | null; type: 'text' | 'check' | 'cross' }>
  }>
  highlight_column?: number | null
}

export interface CTABlock {
  blockType: 'cta'
  heading: string
  description?: string | null
  button?: {
    text?: string | null
    url?: string | null
    style?: 'primary' | 'secondary' | null
  } | null
  style?: 'default' | 'highlight' | 'banner' | null
  background_color?: string | null
}

export interface RichTextBlock {
  blockType: 'richtext'
  content: unknown
}
