/**
 * Referral-link attribution, shared by every entry point that needs to
 * know "did this visitor arrive via an agent's link?" — the contact form,
 * the phone-call click tracker, and the Stripe checkout.
 *
 * The cookie itself just holds the raw `referral_code` from the URL
 * (`?ref=xxxxxxxx`), set by `middleware.ts` on any public page — resolving
 * it to an actual agent happens here, lazily, only where it's needed, to
 * avoid a DB round-trip on every single page navigation.
 */
import { createClient } from '@supabase/supabase-js'

export const REFERRAL_COOKIE = 'greenter_ref'
export const REFERRAL_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 24 * 30 // 30 jours

// profiles.referral_code is `substr(md5(random()::text), 1, 8)` by default,
// but stay a bit permissive in case it's ever regenerated by hand.
export const REFERRAL_CODE_REGEX = /^[a-zA-Z0-9_-]{1,32}$/

function serviceClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false, autoRefreshToken: false } }
  )
}

export interface ReferralAgent {
  id: string
  full_name: string | null
}

/**
 * Resolve a raw referral code to an approved agent. Uses the service-role
 * client because this is called from public, unauthenticated routes
 * (contact form, call tracker, checkout) that have no agent session for
 * RLS to key off — reading only `id`/`full_name` for an `approved` agent
 * is not sensitive.
 */
export async function resolveReferralCode(code: string | null | undefined): Promise<ReferralAgent | null> {
  if (!code || !REFERRAL_CODE_REGEX.test(code)) return null

  const { data, error } = await serviceClient()
    .from('profiles')
    .select('id, full_name')
    .eq('referral_code', code)
    .eq('status', 'approved')
    .maybeSingle()

  if (error || !data) return null
  return data
}
